import subprocess
import os
from langchain.tools import tool

WORKSPACE_DIR = "/home/houyufei/yfhou/biotoolbenchmark/BioGen_Data/workspace"
SEED_REPO_DIR = "/home/houyufei/yfhou/biotoolbenchmark/BioGen_Data/bio_seeds"

@tool
def get_seed_file_path(filename: str) -> str:
    """
    Returns the full path to a file in the seed repository.
    Use this to get paths for reference genomes, annotations, etc.
    """
    path = os.path.join(SEED_REPO_DIR, filename)
    if not os.path.exists(path):
        raise FileNotFoundError(f"Seed file '{filename}' not found in '{SEED_REPO_DIR}'.")
    return path

@tool
def simulate_metagenome_insilicoseq(
    genome_list_file: str, 
    total_reads: int = 1000000, 
    abundance_model: str = "lognormal"
) -> tuple[str, str]:
    """
    使用 InSilicoSeq (iss) 模拟宏基因组双端 reads。
    需要一个文件，每行包含一个基因组FASTA文件的路径。
    丰度将根据指定的模型（如'lognormal', 'uniform'等）随机生成。
    返回生成的两个 FASTQ 文件路径。
    """
    print(f"🧬 Simulating metagenomic reads with InSilicoSeq...")
    
    output_prefix = os.path.join(WORKSPACE_DIR, "iss_metagenome")
    if not os.path.exists(output_prefix):
        os.makedirs(output_prefix)
        
    r1_path = output_prefix + "_R1.fastq"
    r2_path = output_prefix + "_R2.fastq"
    
    # iss generate --genomes <list_file> --n_reads <num> --model wgsim -o <out_prefix> --abundance <model>
    cmd = [
        "conda", "run", "-n", "issenv", "iss", "generate",
        "--genomes", genome_list_file,
        "--n_reads", str(total_reads),
        "--model", "hiseq",  # 使用 HiSeq 模型
        "--cpus", "4",
        "--quiet",
        "--abundance", abundance_model,
        "-o", output_prefix,
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"InSilicoSeq failed: {result.stderr}")
        
    # InSilicoSeq 生成的文件名是 prefix_R1.fastq 和 prefix_R2.fastq
    print(f"✅ Metagenomic reads generated by InSilicoSeq at: {r1_path}, {r2_path}")
    return r1_path, r2_path

@tool
def create_genome_list_file(genome_paths: list[str]) -> str:
    """
    创建一个临时的基因组列表文件，供InSilicoSeq等工具使用。
    genome_paths: 一个包含种子仓库中基因组文件名的列表。
    返回创建的列表文件的路径。
    """
    file_path = os.path.join(WORKSPACE_DIR, "genome_list.txt")
    with open(file_path, 'w') as f:
        for genome_name in genome_paths:
            # full_path = get_seed_file_path(genome_name) # 复用已有的工具
            full_path = os.path.join(SEED_REPO_DIR, genome_name)
            if not os.path.exists(full_path):
                raise FileNotFoundError(f"Seed file '{genome_name}' not found in '{SEED_REPO_DIR}'.")
            f.write(full_path + '\n')
    print(f"✅ Created genome list file at: {file_path}")
    return file_path