import subprocess
import os
from langchain.tools import tool

WORKSPACE_DIR = "/home/houyufei/yfhou/biotoolbenchmark/BioGen_Data/workspace"
SEED_REPO_DIR = "/home/houyufei/yfhou/biotoolbenchmark/BioGen_Data/bio_seeds"

@tool
def simulate_rna_seq_reads_art(
    reference_transcriptome_fasta: str, 
    num_reads_per_transcript: int = 50,
    read_length: int = 100
) -> tuple[str, str]:
    """
    使用 art_illumina 从转录本参考序列模拟 RNA-Seq 双端 reads。
    这个简单模型为每个转录本生成固定数量的 reads。
    返回生成的两个 FASTQ 文件路径。
    """
    print(f"🧬 Simulating RNA-Seq reads with ART...")
    output_prefix = os.path.join(WORKSPACE_DIR, "art_sim_rna")
    if not os.path.exists(output_prefix):
        os.makedirs(output_prefix)
    r1_path = output_prefix + "1.fq"
    r2_path = output_prefix + "2.fq"
    
    # art_illumina -i <input> -p -l <len> -f <fold_coverage> -m <mean_frag> -s <std_dev_frag> -o <out_prefix>
    cmd = [
        "conda", "run", "-n", "bio_agent_env", "art_illumina",
        "-ss", "HS25",  # 使用内置的HiSeq 2500 profile
        "-i", reference_transcriptome_fasta,
        "-p",  # 生成配对末端 reads
        "-l", str(read_length),
        "-f", str(num_reads_per_transcript), # 这里 'f' 代表 "fold coverage", 近似于每个转录本的reads数
        "-m", "300", # 平均片段长度
        "-s", "50",  # 片段长度标准差
        "-o", output_prefix,
    ]
    print(f"ART command: {' '.join(cmd)}")
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"ART Illumina failed: {result.stderr}\n{result.stdout}")
        
    # ART生成的文件名是 prefix + '1.fq' 和 '2.fq'
    print(f"✅ RNA-Seq reads generated by ART at: {r1_path}, {r2_path}")
    return r1_path, r2_path

@tool
def simulate_rna_seq_reads_rsem(
    reference_transcriptome_fasta: str,
    total_reads: int = 1000000
) -> tuple[str, str]:
    """
    使用 RSEM 的 rsem-simulate-reads 模拟 RNA-Seq 双端 reads。
    RSEM可以基于模型文件模拟更真实的表达分布。此工具将使用默认的均匀表达。
    返回生成的两个 FASTQ 文件路径。
    """
    print("🧬 Simulating RNA-Seq reads with RSEM...")
    # RSEM需要一个特定的参考索引
    ref_name = "rsem_ref"
    ref_path = os.path.join(WORKSPACE_DIR, ref_name)
    # 1. 准备RSEM参考
    if not os.path.exists(ref_path + ".grp"):
        print(f"⏳ Preparing RSEM reference for {reference_transcriptome_fasta}...")
        cmd_prep = ["conda", "run", "-n", "bio_agent_env","rsem-prepare-reference", "--quiet", reference_transcriptome_fasta, ref_path]
        subprocess.run(cmd_prep, check=True)

    # 2. 模拟 reads
    output_prefix = os.path.join(WORKSPACE_DIR, "rsem_sim")
    if not os.path.exists(output_prefix):
        os.makedirs(output_prefix)
    r1_path = output_prefix + "_1.fq"
    r2_path = output_prefix + "_2.fq"

    # rsem-simulate-reads <ref_name> <model_file> <isoform.results> <theta> <N> <output_name>
    # 这里我们不提供模型文件，RSEM会使用默认的均匀分布
    # `rsem-calculate-expression` 的输出可以作为模型文件，但为了简化，我们跳过这一步
    # 我们需要创建一个虚拟的 isoform.results 文件头
    isoform_results_path = os.path.join(WORKSPACE_DIR, "dummy.isoforms.results")
    with open(isoform_results_path, 'w') as f:
        f.write("transcript_id\tgene_id\tlength\teffective_length\tFPKM\tTPM\tIsoPct\n")
    
    cmd_sim = [
        "conda", "run", "-n", "bio_agent_env",
        "rsem-simulate-reads",
        ref_path,
        isoform_results_path, # 提供一个空的但有头部的结果文件
        "0.1", # theta value
        str(total_reads),
        output_prefix
    ]
    
    result = subprocess.run(cmd_sim, capture_output=True, text=True)
    if "Can not open" in result.stderr or result.returncode != 0:
        raise RuntimeError(f"RSEM simulation failed: {result.stderr}")

    print(f"✅ RNA-Seq reads generated by RSEM at: {r1_path}, {r2_path}")
    return r1_path, r2_path